---
version: '3'
services:
  actistat_client:
#    image: actistat-2-15-1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://${DOCKER_CLIENT_NAME}:umami@db:5432/${DOCKER_CLIENT_NAME}
        DATABASE_TYPE: postgresql
        APP_SECRET: ${DOCKER_APP_SECRET}
        TRACKER_SCRIPT_NAME: "umami"
    container_name: actistat_${DOCKER_CLIENT_NAME}
    ports:
      - "${DOCKER_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${DOCKER_CLIENT_NAME}:umami@db:5432/${DOCKER_CLIENT_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${DOCKER_APP_SECRET}
      TRACKER_SCRIPT_NAME: "umami"
    depends_on:
      db_postgre_client:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${DOCKER_PORT}/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db_postgre_client:
    image: postgres:15-alpine
    container_name: db_postgre_${DOCKER_CLIENT_NAME}
    environment:
      POSTGRES_DB: ${DOCKER_CLIENT_NAME}
      POSTGRES_USER: ${DOCKER_CLIENT_NAME}
      POSTGRES_PASSWORD: umami
    volumes:
      - actistat-db-data_${DOCKER_CLIENT_NAME}:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DOCKER_CLIENT_NAME} -d $${DOCKER_CLIENT_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backup_client:
    image: alpine:latest
    container_name: backup_${DOCKER_CLIENT_NAME}
    volumes:
      - ./backups/${DOCKER_CLIENT_NAME}:/backups
    environment:
      POSTGRES_DB: ${DOCKER_CLIENT_NAME}
      POSTGRES_USER: ${DOCKER_CLIENT_NAME}
      POSTGRES_PASSWORD: "umami"
    entrypoint: [ "/bin/sh", "-c", "crond -f -l 2" ]
    depends_on:
      - db_postgre_client
    restart: always
    command: |
      sh -c 'echo "0 3 * * * pg_dump -h dbpostgresql_${DOCKER_CLIENT_NAME} -U ${DOCKER_CLIENT_NAME} -d ${DOCKER_CLIENT_NAME} | gzip > /backups/backup_$(date +\%F).sql.gz && find /backups -type f -mtime +7 -delete" | crontab - && crond -f -l 2'

volumes:
  actistat-db-data_setram:
