version: '3'

networks:
  pgbouncer:
    external: true

services:
  actistat_client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://${CLIENT_NAME}:${DB_PASSWORD}@pgbouncer_global:6432/${CLIENT_NAME}
        DATABASE_TYPE: postgresql
        APP_SECRET: ${APP_SECRET}
        TRACKER_SCRIPT_NAME: "umami"
    # On utilise container_name pour avoir des noms uniques grâce aux variables
    container_name: actistat_${CLIENT_NAME}
    ports:
      - "${PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${CLIENT_NAME}:${DB_PASSWORD}@pgbouncer_global:6432/${CLIENT_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
      TRACKER_SCRIPT_NAME: "umami"
    init: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000/api/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pgbouncer
